package com.jsos.randomverse2.bible;

import java.util.ArrayList;

import com.jsos.randomverse2.models.Verse;

/**
 * Created by JHESE154 on 8/24/2016.
 * A class that holds the Bible verses to be shown on the user
 */
public class BibleV1 {
    public final static ArrayList<Verse> versesQuery = new ArrayList<Verse>();
    public static final int VERSE_COUNT = 98;  // hardcoded for optimization. Fix this everytime
    public static final double VERSION = 1.0;  // support for future updates

    public static ArrayList<Verse> generateQuery() {
        // JSON
        versesQuery.add(new Verse(0, "1 Corinthians 10:13", "No temptation has seized you except what is common to man. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can stand up under it.", "Wala pang pagsubok na dumating sa inyo na hindi nararanasan ng lahat ng tao. Tapat ang Diyos, at hindi niya ipapahintulot na kayo'y subukin nang higit sa inyong makakaya. Sa halip, pagdating ng pagsubok, bibigyan niya kayo ng lakas upang mapagtagumpayan iyon."));
        versesQuery.add(new Verse(1, "1 Corinthians 6:19", "Do you not know that your body is a temple of the Holy Spirit, who is in you, whom you have received from God? You are not your own;", "Hindi ba ninyo alam na ang inyong katawan ay templo ng Espiritu Santo na nasa inyo at ipinagkaloob ng Diyos sa inyo? Hindi na ninyo pag-aari ang inyong katawan;"));
        versesQuery.add(new Verse(2, "1 John 1:9", " If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", "Subalit kung ipinapahayag natin sa Diyos ang ating mga kasalanan, maaasahan nating patatawarin tayo ng Diyos sa mga ito, at lilinisin tayo sa lahat ng ating kasalanan, sapagkat siya'y tapat at matuwid."));
        versesQuery.add(new Verse(3, "1 John 3:16", "This is how we know what love is: Jesus Christ laid down his life for us. And we ought to lay down our lives for our brothers.", "Dito natin nakikilala ang tunay na pag-ibig: inialay ni Cristo ang kanyang buhay para sa atin. Kaya't dapat din nating ialay ang ating buhay para sa kapatiran."));
        versesQuery.add(new Verse(4, "1 Peter 2:24", "He himself bore our sins in his body on the tree, so that we might die to sins and live for righteousness; by his wounds you have been healed.", "Sa kanyang pagkamatay sa krus, pinasan niya ang bigat ng ating mga kasalanan upang tayo'y mamatay na sa kasalanan at mamuhay ayon sa kalooban ng Diyos. Kayo'y pinagaling na sa pamamagitan ng kanyang mga sugat."));
        versesQuery.add(new Verse(5, "1 Peter 3:15", "But in your hearts set apart Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect,", "Igalang ninyo si Cristo mula sa inyong puso at sambahin ninyo siya bilang Panginoon. Lagi kayong maging handang magpaliwanag sa sinumang magtatanong sa inyo tungkol sa pag-asa na nasa inyo."));
        versesQuery.add(new Verse(6, "1 Peter 5:7", "Cast all your anxiety on him because he cares for you.", "Ipagkatiwala ninyo sa kanya ang inyong mga alalahanin sa buhay sapagkat siya ay nagmamalasakit sa inyo."));
        versesQuery.add(new Verse(7, "2 Corinthians 12:9", "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.' Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me.", "ganito ang kanyang sagot, 'Ang pagpapala ko ay sapat sa lahat ng pangangailangan mo; lalong nahahayag ang aking kapangyarihan kung ikaw ay mahina.' Kaya't buong galak kong ipagmamalaki ang aking mga kahinaan upang lalo kong madama ang kapangyarihan ni Cristo."));
        versesQuery.add(new Verse(8, "2 Corinthians 5:17", "Therefore, if anyone is in Christ, he is a new creation; the old has gone, the new has come!", "Kaya't kung nakipag-isa na kay Cristo ang isang tao, isa na siyang bagong nilalang. Wala na ang dati niyang pagkatao, sa halip, ito'y napalitan na ng bago."));
        versesQuery.add(new Verse(9, "2 Corinthians 5:21", "God made him who had no sin to be sin for us, so that in him we might become the righteousness of God.", "Hindi nagkasala si Cristo, ngunit dahil sa atin, siya'y itinuring na makasalanan upang sa pamamagitan niya ay maging matuwid tayo sa harap ng Diyos."));
        versesQuery.add(new Verse(10, "2 Peter 1:4", "Through these he has given us his very great and precious promises, so that through them you may participate in the divine nature and escape the corruption in the world caused by evil desires.", "Sa paraang ito ay binigyan niya tayo ng mga dakila at napakahalagang pangako upang makaiwas tayo sa nakakasirang pagnanasa sa sanlibutang ito at upang makabahagi tayo sa kanyang likas bilang Diyos."));
        versesQuery.add(new Verse(11, "2 Timothy 1:7", "For God did not give us a spirit of timidity, but a spirit of power, of love and of self-discipline.", "Sapagkat ang Espiritung ibinigay sa atin ng Diyos ay hindi espiritu ng kahinaan ng loob, kundi espiritu ng kapangyarihan, pag-ibig at pagpipigil sa sarili."));
        versesQuery.add(new Verse(12, "2 Timothy 3:16", "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness,", "Ang lahat ng Kasulatan ay kinasihan ng Diyos, at nagagamit sa pagtuturo ng katotohanan, sa pagtatama sa maling katuruan, sa pagtutuwid sa likong gawain at sa pagsasanay para sa matuwid na pamumuhay,"));
        versesQuery.add(new Verse(13, "Acts 17:11", "Now the Bereans were of more noble character than the Thessalonians, for they received the message with great eagerness and examined the Scriptures every day to see if what Paul said was true.", "Mas bukás ang isipan ng mga Judiong tagaroon kaysa sa mga Judiong taga-Tesalonica. Wiling-wili silang nakikinig sa mga paliwanag ni Pablo, at sinasaliksik nila araw-araw ang mga Kasulatan upang tingnan kung totoo nga ang sinasabi niya."));
        versesQuery.add(new Verse(14, "Acts 18:10", "For I am with you, and no one is going to attack and harm you, because I have many people in this city.", "sapagkat ako'y nasa iyo. Hindi ka maaano sapagkat marami akong tagasunod sa lunsod na ito."));
        versesQuery.add(new Verse(15, "Acts 18:11", "So Paul stayed for a year and a half, teaching them the word of God.", "Tumigil nga siya roon at ipinangaral niya ang salita ng Diyos sa loob ng isang taon at kalahati."));
        versesQuery.add(new Verse(16, "Acts 18:9", "One night the Lord spoke to Paul in a vision: “Do not be afraid; keep on speaking, do not be silent.", "Isang gabi, sinabi ng Panginoon kay Pablo sa pamamagitan ng isang pangitain, “Huwag kang matakot! Ipagpatuloy mo ang iyong pangangaral! Anuman ang mangyari'y huwag kang titigil"));
        versesQuery.add(new Verse(17, "Acts 1:8", "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.", "Subalit tatanggap kayo ng kapangyarihan pagbaba sa inyo ng Espiritu Santo, at kayo'y magiging mga saksi ko sa Jerusalem, sa buong Judea at sa Samaria, at hanggang sa dulo ng daigdig."));
        versesQuery.add(new Verse(18, "Acts 2:38", "Peter replied, “Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.", "Sumagot si Pedro, “Pagsisihan ninyo't talikuran ang inyong mga kasalanan at magpabautismo kayo sa pangalan ni Jesu-Cristo upang kayo'y patawarin; at ipagkakaloob sa inyo ang Espiritu Santo."));
        versesQuery.add(new Verse(19, "Acts 4:12", "Salvation is found in no one else, for there is no other name under heaven given to men by which we must be saved.", "Sa kanya lamang matatagpuan ang kaligtasan, sapagkat walang ibang pangalan ng sinumang tao sa buong mundo na ibinigay ng Diyos sa mga tao upang tayo ay maligtas."));
        versesQuery.add(new Verse(20, "Colosians 3:12", "Therefore, as God’s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.", "Kaya nga, dahil kayo'y hinirang ng Diyos, minamahal niya at pinili para sa kanya, dapat kayong maging mahabagin, mabait, mapagpakumbabá, mahinahon, at mapagtiis."));
        versesQuery.add(new Verse(21, "Colosians 3:23", "Whatever you do, work at it with all your heart, as working for the Lord, not for men,", "Anuman ang inyong ginagawa, gawin ninyo nang buong puso na parang sa Panginoon kayo naglilingkod at hindi sa tao."));
        versesQuery.add(new Verse(22, "Ephesians 2:10", "For we are God’s workmanship, created in Christ Jesus to do good works, which God prepared in advance for us to do.", "Sapagkat tayo'y nilalang ng Diyos; nilikha sa pamamagitan ni Cristo Jesus upang iukol natin ang ating buhay sa paggawa ng mabuti. Iyan ang layuning pinili ng Diyos para sa atin noong una pa man."));
        versesQuery.add(new Verse(23, "Ephesians 2:8", "For it is by grace you have been saved, through faith—and this not from yourselves, it is the gift of God—", "Sapagkat dahil sa kagandahang-loob ng Diyos kayo ay naligtas sa pamamagitan ng pananampalataya; at ang kaligtasang ito'y kaloob ng Diyos at hindi sa pamamagitan ng inyong sarili;"));
        versesQuery.add(new Verse(24, "Ephesians 2:9", "not by works, so that no one can boast.", "hindi ito bunga ng inyong mga gawa kaya't walang dapat ipagmalaki ang sinuman."));
        versesQuery.add(new Verse(25, "Ephesians 3:20", "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us,", "Sa kanya na makakagawa nang higit pa kaysa maaari nating hilingin at isipin, sa pamamagitan ng kanyang kapangyarihang naghahari sa atin;"));
        versesQuery.add(new Verse(26, "Galatians 2:20", "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loved me and gave himself for me.", "Hindi na ako ang nabubuhay ngayon kundi si Cristo na ang nabubuhay sa akin. At habang ako'y nabubuhay pa sa katawang-lupa, mamumuhay ako sa pananalig sa Anak ng Diyos na umibig sa akin at naghandog ng kanyang buhay para sa akin."));
        versesQuery.add(new Verse(27, "Galatians 5:22", "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness,", "Subalit ang bunga ng Espiritu ay pag-ibig, kagalakan, kapayapaan, katiyagaan, kabaitan, kabutihan, katapatan,"));
        versesQuery.add(new Verse(28, "Galatians 5:23", "gentleness and self-control. Against such things there is no law.", "kahinahunan, at pagpipigil sa sarili. Walang batas laban sa mga ito."));
        versesQuery.add(new Verse(29, "Genesis 1:1", "In the beginning God created the heavens and the earth.", "Nang pasimula ay nilikha ng Diyos ang langit at ang lupa"));
        versesQuery.add(new Verse(30, "Genesis 1:26", "Then God said, “Let us make man in our image, in our likeness, and let them rule over the fish of the sea and the birds of the air, over the livestock, over all the earth, and over all the creatures that move along the ground.", "Pagkatapos, sinabi ng Diyos: 'Ngayon, likhain natin ang tao ayon sa ating larawan, ayon sa ating wangis. Sila ang mamamahala sa mga isda, sa mga ibon sa himpapawid at sa lahat ng hayop, maging maamo o mailap, malaki o maliit.'"));
        versesQuery.add(new Verse(31, "Genesis 1:27", "So God created man in his own image, in the image of God he created him; male and female he created them.", "Nilalang   nga ng Diyos ang tao ayon sa kanyang larawan. Sila'y kanyang nilalang na isang lalaki at isang babae,"));
        versesQuery.add(new Verse(32, "Hebrews 10:25", "Let us not give up meeting together, as some are in the habit of doing, but let us encourage one another—and all the more as you see the Day approaching.", "Kaya't huwag kayong mawawalan ng pananampalataya sa Diyos, sapagkat dakila ang naghihintay na gantimpala para sa inyo."));
        versesQuery.add(new Verse(33, "Hebrews 11:1", "Now faith is being sure of what we hope for and certain of what we do not see.", "Dahil din sa pananampalataya na iyan, itinatag niya ang Paskwa at iniutos sa mga Israelita na pahiran ng dugo ang pintuan ng kanilang mga bahay upang huwag patayin ng Anghel na Mamumuksa ang kanilang mga panganay."));
        versesQuery.add(new Verse(34, "Hebrews 11:6", "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.", "Kung hindi tayo sumasampalataya sa Diyos, hindi natin siya mabibigyang kaluguran, sapagkat ang sinumang lumalapit sa Diyos ay dapat sumampalatayang may Diyos na nagbibigay ng gantimpala sa mga nananalig sa kanya."));
        versesQuery.add(new Verse(35, "Hebrews 12:1", "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles, and let us run with perseverance the race marked out for us.", "Kaya nga, dahil napapaligiran tayo ng napakaraming saksi, talikuran natin ang kasalanan at ang anumang balakid na pumipigil sa atin. Buong tiyaga tayong tumakbo sa paligsahang ating sinalihan."));
        versesQuery.add(new Verse(36, "Hebrews 12:2", "Let us fix our eyes on Jesus, the author and perfecter of our faith, who for the joy set before him endured the cross, scorning its shame, and sat down at the right hand of the throne of God.", "Ituon natin ang ating paningin kay Jesus na siyang pinagmumulan at kabuuan ng ating pananampalataya. Dahil sa kagalakang naghihintay sa kanya, hindi niya ikinahiya ang mamatay sa krus, at siya ngayo'y nakaupo sa kanan ng trono ng Diyos."));
        versesQuery.add(new Verse(37, "Hebrews 13:5", "Keep your lives free from the love of money and be content with what you have, because God has said, “Never will I leave you; never will I forsake you.", "Huwag kayong magmukhang pera; at masiyahan na kayo sa anumang nasa inyo. Sapagkat sinabi ng Diyos, 'Hindi kita iiwan ni pababayaan man'"));
        versesQuery.add(new Verse(38, "Hebrews 4:12", "For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.", "Ang salita ng Diyos ay buháy at mabisa, mas matalas kaysa alinmang tabak na sa magkabila'y may talim. Ito'y tumatagos maging sa kaibuturan ng kaluluwa at espiritu, ng mga kasukasuan at buto, at nakakaalam ng mga iniisip at binabalak ng tao."));
        versesQuery.add(new Verse(39, "Hebrews 4:15", "For we do not have a high priest who is unable to sympathize with our weaknesses, but we have one who has been tempted in every way, just as we are—yet was without sin.", "Ang ating Pinakapunong Paring ito ay nakakaunawa sa ating mga kahinaan sapagkat tulad natin, tinukso siya sa lahat ng paraan, subalit kailanma'y hindi siya nagkasala."));
        versesQuery.add(new Verse(40, "Hebrews 4:16", "Let us then approach the throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.", "Kaya't huwag tayong mag-atubiling lumapit sa trono ng mahabaging Diyos upang makamtan natin ang habag at kalinga sa panahon ng ating pangangailangan."));
        versesQuery.add(new Verse(41, "Isaiah 26:3", "You will keep in perfect peace him whose mind is steadfast, because he trusts in you.", "Binibigyan mo ng lubos na kapayapaan ang mga may matatag na paninindigan at sa iyo'y nagtitiwala."));
        versesQuery.add(new Verse(42, "Isaiah 40:31", "but those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", "Ngunit muling lumalakas at sumisigla ang nagtitiwala kay Yahweh."));
        versesQuery.add(new Verse(43, "Isaiah 41:10", "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.", "Ako'y sasaiyo, huwag kang matakot, ako ang iyong Diyos, hindi ka dapat mangamba. Palalakasin kita at tutulungan, iingatan at ililigtas."));
        versesQuery.add(new Verse(44, "Isaiah 53:4", "Surely he took up our infirmities and carried our sorrows, yet we considered him stricken by God, smitten by him, and afflicted.", "Tunay ngang inalis niya ang ating mga kahinaan, pinagaling niya ang ating mga karamdaman. Subalit inakala nating iyo'y parusa ng Diyos sa kanya."));
        versesQuery.add(new Verse(45, "Isaiah 53:5", "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was upon him, and by his wounds we are healed.", "Ngunit dahil sa ating mga kasalanan kaya siya nasugatan; siya ay binugbog dahil sa ating kasamaan. Tayo ay gumaling dahil sa pahirap na dinanas niya at sa mga hampas na kanyang tinanggap."));
        versesQuery.add(new Verse(46, "Isaiah 53:6", "We all, like sheep, have gone astray, each of us has turned to his own way; and the LORD has laid on him the iniquity of us all.", "Tayong lahat ay tulad ng mga tupang naliligaw; nagkanya-kanya tayo ng lakad. Ngunit ipinataw ni Yahweh sa kanya ang kaparusahang tayo ang dapat tumanggap."));
        versesQuery.add(new Verse(47, "Isaiah 55:8", "For my thoughts are not your thoughts, neither are your ways my ways,” declares the LORD.", "Ang sabi ni Yahweh, \"Ang aking kaisipa'y hindi ninyo kaisipan, ang inyong kaparaanan ay hindi ko kaparaanan.\""));
        versesQuery.add(new Verse(48, "James 1:12", "Blessed is the man who perseveres under trial, because when he has stood the test, he will receive the crown of life that God has promised to those who love him.", "Mapalad ang taong nananatiling tapat sa kabila ng mga pagsubok; sapagkat matapos siyang subukin, tatanggap siya ng gantimpala ng buhay, na ipinangako ng Panginoon sa mga umiibig sa kanya."));
        versesQuery.add(new Verse(49, "James 1:2", "Consider it pure joy, my brothers, whenever you face trials of many kinds,", "Mga kapatid, magalak kayo kapag kayo'y dumaranas ng iba't ibang uri ng pagsubok."));
        versesQuery.add(new Verse(50, "James 1:3", "because you know that the testing of your faith develops perseverance.", "Dapat ninyong malaman na napatatatag ang ating pananampalataya sa pamamagitan ng mga pagsubok."));
        versesQuery.add(new Verse(51, "James 5:16", "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous man is powerful and effective.", "Kaya nga, ipagtapat ninyo sa inyong mga kapatid ang inyong mga kasalanan at ipanalangin ninyo ang isa't isa, upang kayo'y gumaling. Malaki ang nagagawa ng panalangin ng taong matuwid."));
        versesQuery.add(new Verse(52, "Jeremiah 29:11", "'For I know the plans I have for you', declares the LORD, 'plans to prosper you and not to harm you, plans to give you hope and a future.'", "Sapagkat batid kong lubos ang mga plano ko para sa inyo; mga planong hindi ninyo ikakasama kundi para sa inyong ikabubuti. Ito'y mga planong magdudulot sa inyo ng kinabukasang punung-puno ng pag-asa."));
        versesQuery.add(new Verse(53, "John 10:10", "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.", "Dumarating ang magnanakaw para lamang magnakaw, pumatay, at manira. Naparito ako upang ang mga tupa ay magkaroon ng buhay, ng isang buhay na masagana at ganap."));
        versesQuery.add(new Verse(54, "John 11:25", "Jesus said to her, \"I am the resurrection and the life. He who believes in me will live, even though he dies;\"", "Sinabi sa kanya ni Jesus, \"Ako ang nagbibigay-buhay at muling pagkabuhay. Ang sinumang sumasampalataya sa akin, kahit mamatay ay muling mabubuhay;\""));
        versesQuery.add(new Verse(55, "John 13:35", "By this all men will know that you are my disciples, if you love one another.", "Kung kayo'y mag-iibigan, makikilala ng lahat na kayo'y mga alagad ko."));
        versesQuery.add(new Verse(56, "John 14:27", "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", "Kapayapaan ang iniiwan ko sa inyo. Ang aking kapayapaan ang ibinibigay ko sa inyo; hindi ito katulad ng kapayapaang ibinibigay ng mundo. Huwag na kayong mabalisa; huwag na kayong matakot."));
        versesQuery.add(new Verse(57, "John 14:6", "Jesus answered, “I am the way and the truth and the life. No one comes to the Father except through me.", "Sumagot si Jesus, “Ako ang daan, ang katotohanan, at ang buhay. Walang makakapunta sa Ama kundi sa pamamagitan ko."));
        versesQuery.add(new Verse(58, "John 15:13", "Greater love has no one than this, that he lay down his life for his friends.", "Walang pag-ibig na hihigit pa kaysa pag-ibig ng isang taong nag-aalay ng kanyang buhay para sa kanyang mga kaibigan."));
        versesQuery.add(new Verse(59, "John 16:33", "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", "Sinabi ko ito sa inyo upang kayo'y magkaroon ng kapayapaan sa pakikipag-isa sa akin. Magdaranas kayo ng kapighatian sa mundong ito, ngunit tibayan ninyo ang inyong loob! Napagtagumpayan ko na ang sanlibutan!"));
        versesQuery.add(new Verse(60, "John 1:1", "In the beginning was the Word, and the Word was with God, and the Word was God.", "Nang pasimula ay naroon na ang Salita; ang Salita ay kasama ng Diyos, at ang Salita ay Diyos."));
        versesQuery.add(new Verse(61, "John 1:12", "Yet to all who received him, to those who believed in his name, he gave the right to become children of God—", "Subalit ang lahat ng tumanggap at sumampalataya sa kanya ay binigyan niya ng karapatang maging mga anak ng Diyos."));
        versesQuery.add(new Verse(62, "John 3:16", "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", "Sapagkat gayon na lamang ang pag-ibig ng Diyos sa sangkatauhan, kaya't ibinigay niya ang kanyang kaisa-isang Anak, upang ang sinumang sumampalataya sa kanya ay hindi mapahamak, kundi magkaroon ng buhay na walang hanggan."));
        versesQuery.add(new Verse(63, "John 3:17", "For God did not send his Son into the world to condemn the world, but to save the world through him.", "Isinugo ng Diyos ang kanyang Anak, hindi upang hatulang maparusahan ang mga tao, kundi upang iligtas ang mga ito sa pamamagitan niya."));
        versesQuery.add(new Verse(64, "John 5:24", "I tell you the truth, whoever hears my word and believes him who sent me has eternal life and will not be condemned; he has crossed over from death to life.", "Pakatandaan ninyo: ang nakikinig sa aking salita at sumasampalataya sa nagsugo sa akin ay may buhay na walang hanggan. Hindi na siya hahatulan, sa halip ay inilipat na siya sa buhay mula sa kamatayan."));
        versesQuery.add(new Verse(65, "Joshua 1:8", "Do not let this Book of the Law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful.", "Huwag mong kaliligtaang basahin ang aklat ng kautusan. Pagbulay-bulayan mo iyon araw at gabi upang matupad mo ang lahat ng nakasaad doon. Sa ganoon, magiging masagana at matagumpay ang iyong pamumuhay."));
        versesQuery.add(new Verse(66, "Joshua 1:9", "Have I not commanded you? Be strong and courageous. Do not be terrified; do not be discouraged, for the LORD your God will be with you wherever you go.", "Tandaan mo ang bilin ko: Magpakatatag ka at lakasan mo ang iyong loob. Huwag kang matatakot o mawawalan ng pag-asa sapagkat akong si Yahweh, na iyong Diyos, ay kasama mo saan ka man magpunta."));
        versesQuery.add(new Verse(67, "Matthew 11:28", "Come to me, all you who are weary and burdened, and I will give you rest.", "Lumapit kayo sa akin, kayong lahat na nahihirapan at nabibigatang lubha sa inyong pasanin, at kayo'y bibigyan ko ng kapahingahan."));
        versesQuery.add(new Verse(68, "Matthew 11:29", "Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.", "Pasanin ninyo ang aking pamatok at sundin ninyo ang aking mga itinuturo sapagkat ako'y maamo at mapagkumbabang loob. Matatagpuan ninyo sa akin ang kapahingahan"));
        versesQuery.add(new Verse(69, "Matthew 11:30", "For my yoke is easy and my burden is light.", "sapagkat madaling dalhin ang aking pamatok at magaan ang pasaning ibinibigay ko sa inyo."));
        versesQuery.add(new Verse(70, "Matthew 22:37", "Jesus replied: \" Love the Lord your God with all your heart and with all your soul and with all your mind.\"", "Sumagot si Jesus, \"Ibigin mo ang Panginoon mong Diyos nang buong puso, nang buong kaluluwa, at nang buong pag-iisip.\""));
        versesQuery.add(new Verse(71, "Matthew 28:18", "Then Jesus came to them and said, \"All authority in heaven and on earth has been given to me.\"", "Lumapit si Jesus at sinabi sa kanila, \"Ibinigay na sa akin ang lahat ng kapangyarihan sa langit at sa lupa.\""));
        versesQuery.add(new Verse(72, "Matthew 28:19", "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.", "Kaya't habang kayo'y humahayo, gawin ninyong alagad ko ang mga tao sa lahat ng bansa. Bautismuhan ninyo sila sa pangalan ng Ama, at ng Anak, at ng Espiritu Santo."));
        versesQuery.add(new Verse(73, "Matthew 28:20", "and teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age.", "Turuan ninyo silang sumunod sa lahat ng iniutos ko sa inyo. Tandaan ninyo, ako'y laging kasama ninyo hanggang sa katapusan ng panahon."));
        versesQuery.add(new Verse(74, "Matthew 6:33", "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", "Ngunit higit sa lahat ay pagsikapan ninyo na kayo'y pagharian ng Diyos at mamuhay nang ayon sa kanyang kalooban, at ibibigay niya sa inyo ang lahat ng inyong pangangailangan."));
        versesQuery.add(new Verse(75, "Micah 6:8", "He has showed you, O man, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.", "Itinuro na niya sa iyo, kung ano ang mabuti. Ito ang nais ni Yahweh: Maging makatarungan ka sa lahat ng bagay, patuloy mong mahalin ang iyong kapwa, at buong pagpapakumbabang sumunod ka sa iyong Diyos."));
        versesQuery.add(new Verse(76, "Philippians 1:6", "being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.", "Natitiyak kong ang mabuting gawang pinasimulan sa inyo ng Diyos ay kanyang lulubusin hanggang sa araw ng pagbabalik ni Jesu-Cristo."));
        versesQuery.add(new Verse(77, "Philippians 4:13", "I can do everything through him who gives me strength.", "Ang lahat ng ito'y magagawa ko dahil sa lakas na kaloob sa akin ni Cristo."));
        versesQuery.add(new Verse(78, "Philippians 4:19", "And my God will meet all your needs according to his glorious riches in Christ Jesus.", "At buhat sa hindi mauubos na kayamanan ng Diyos, ibibigay niya ang lahat ng inyong kailangan sa pamamagitan ni Cristo Jesus."));
        versesQuery.add(new Verse(79, "Philippians 4:6", "Do not be anxious about anything, but in everything, by prayer and petition, with thanksgiving, present your requests to God.", "Huwag kayong mabalisa tungkol sa anumang bagay. Sa halip, hingin ninyo sa Diyos ang lahat ng inyong kailangan sa pamamagitan ng panalanging may pasasalamat."));
        versesQuery.add(new Verse(80, "Philippians 4:8", "Finally, brothers, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.", "Bilang pagtatapos, mga kapatid, dapat maging laman ng inyong isip ang mga bagay na karapat-dapat at kapuri-puri: mga bagay na totoo, marangal, matuwid, malinis, kaibig-ibig, at kagalang-galang."));
        versesQuery.add(new Verse(81, "Philippians 4:9", "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", "Isagawa ninyo ang lahat ng inyong natutuhan, tinanggap, narinig at nakita sa akin. Sa gayon, sasainyo ang Diyos na nagbibigay ng kapayapaan."));
        versesQuery.add(new Verse(82, "Proverbs 3:5", "Trust in the LORD with all your heart and lean not on your own understanding.", "Kay Yahweh ka magtiwala, buong puso at lubusan, at huwag kang mananangan sa sariling karunungan."));
        versesQuery.add(new Verse(83, "Proverbs 3:6", "in all your ways acknowledge him, and he will make your paths straight.", "Sa lahat ng iyong gawain siya nga'y alalahanin, upang ika'y patnubayan sa iyong mga tatahakin."));
        versesQuery.add(new Verse(84, "Psalm 133:3", "It is as if the dew of Hermon were falling on Mount Zion. For there the LORD bestows his blessing, even life forevermore.", "Katulad din ito'y hamog sa umaga, sa Bundok ng Hermon, hamog na dumilig sa dakong maburol na Bundok ng Zion; sa lugar na ito, nangako si Yahweh, ang pangakong buhay na mananatili."));
        versesQuery.add(new Verse(85, "Psalms 133:1", "How good and pleasant it is when brothers live together in unity!", "Napakaligaya at kahanga-hanga sa ating pangmasid, ang nagkakaisa't laging sama-sama na magkakapatid!"));
        versesQuery.add(new Verse(86, "Psalms 133:2", "It is like precious oil poured on the head, running down on the beard, running down on Aaron’s beard, down upon the collar of his robes.", "Langis ng olibo, ang nakakatulad at nakakawangis, sa ulo at balbas nitong si Aaron kapag ipinahid, umaagos ito't nababasa pati ang suot na damit."));
        versesQuery.add(new Verse(87, "Psalms 37:4", "Delight yourself in the LORD and he will give you the desires of your heart.", "Kay Yahweh mo hanapin ang kaligayahan, at ang pangarap mo'y iyong makakamtan."));
        versesQuery.add(new Verse(88, "Romans 10:17", "Consequently, faith comes from hearing the message, and the message is heard through the word of Christ.", "Kaya't ang pananampalataya ay bunga ng pakikinig, at ang pakikinig naman ay bunga ng pangangaral tungkol kay Cristo."));
        versesQuery.add(new Verse(89, "Romans 10:9", "That if you confess with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved.", "Kung ipahahayag ng iyong labi na si Jesus ay Panginoon at buong puso kang sasampalataya na siya'y muling binuhay ng Diyos, maliligtas ka."));
        versesQuery.add(new Verse(90, "Romans 12:1", "Therefore, I urge you, brothers, in view of God’s mercy, to offer your bodies as living sacrifices, holy and pleasing to God—this is your spiritual act of worship.", "Kaya nga, mga kapatid, alang-alang sa masaganang habag ng Diyos sa atin, ako'y nakikiusap na ialay ninyo ang inyong sarili bilang isang handog na buháy, banal at kalugud-lugod sa Diyos. Ito ang karapat-dapat na pagsamba ninyo sa Diyos. "));
        versesQuery.add(new Verse(91, "Romans 12:2", "Do not conform any longer to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is—his good, pleasing and perfect will.", "Huwag kayong makiayon sa takbo ng mundong ito. Mag-iba kayo sa pamamagitan ng pagbabago ng inyong pag-iisip upang maunawaan ninyo ang kalooban ng Diyos; kung ano ang mabuti, kalugud-lugod at ganap na kalooban niya."));
        versesQuery.add(new Verse(92, "Romans 15:13", "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.", "Puspusin nawa kayo ng Diyos na siyang bukal ng pag-asa, at nawa ay pagkalooban niya kayo ng kagalakan at kapayapaan sa pamamagitan ng inyong pananampalataya, upang mag-umapaw ang inyong pag-asa sa pamamagitan ng kapangyarihan ng Espiritu Santo."));
        versesQuery.add(new Verse(93, "Romans 3:23", "for all have sinned and fall short of the glory of God,", "Sapagkat ang lahat ay nagkasala, at walang sinumang nakaabot sa kaluwalhatian ng Diyos."));
        versesQuery.add(new Verse(94, "Romans 5:8", "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", "Ngunit ipinadama ng Diyos ang kanyang pag-ibig sa atin nang mamatay si Cristo para sa atin noong tayo'y makasalanan pa."));
        versesQuery.add(new Verse(95, "Romans 6:23", "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", "Sapagkat kamatayan ang kabayaran ng kasalanan, ngunit ang libreng kaloob ng Diyos ay buhay na walang hanggan, sa pamamagitan ni Cristo Jesus na ating Panginoon."));
        versesQuery.add(new Verse(96, "Romans 8:28", "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", "Alam nating sa lahat ng bagay ay gumagawa ang Diyos para sa ikabubuti ng mga nagmamahal sa kanya, silang mga tinawag ayon sa kanyang layunin."));
        versesQuery.add(new Verse(97, "Romans 8:38", "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers,", "Sapagkat natitiyak kong walang makapaghihiwalay sa atin sa kanyang pag-ibig. Kahit ang kamatayan, ang buhay, ang mga anghel, ang mga pamunuan o ang mga kapangyarihan, ang kasalukuyan o ang hinaharap,"));
        versesQuery.add(new Verse(98, "Romans 8:39", "neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.", "ang kataasan, ang kalaliman, o alinmang nilalang ay hindi makapaghihiwalay sa atin sa pag-ibig ng Diyos na ipinagkaloob sa atin sa pamamagitan ni Cristo Jesus na ating Panginoon."));

        return versesQuery;
    }
}
